### ISSUE TITLE
Wrong colours

### ISSUE THREAD

**Issue by Kezii** [trehn/termtrack#3]
Hi,
I've been using termtrack sporadically for years, but recently I incurred in a bug that I was not able to solve

![immagine](https://user-images.githubusercontent.com/3357750/56093517-13329e80-5eca-11e9-9025-4f6865e3a87f.png)
The colours are all wrong, i'm using the command that is written on the readme so it should show the earth all shaded etc, but it doesn't.
The terminal (konsole) correctly displays colors

Can anyone reproduce?

**Comment by xanderificnl** [comment]
Is this still an issue? In Konsole 18.04.0 here with the default profile it works. Termtrack only crashes on resizing the window.
